### ISSUE TITLE
01월 17일 ~ 01월 23일차 알고리즘 문제 출제

### ISSUE THREAD

**Issue by hwang434** [ROUTINE-STUDY/Algorithm#231]
출제 문제 유형 : 완전탐색

- [완전탐색/Bronze2] : https://www.acmicpc.net/problem/2309
- [완전탐색/Silver5] : https://www.acmicpc.net/problem/1018

### 참고하면 좋은 자료
- 완전 탐색 관련 : https://blog.naver.com/kks227/220769870195
- 완전 탐색 관련 : https://swycha.tistory.com/133

### 잡담
 - 오랜만에 다시 시작하는 관계로 이번 주는 2문제만 내겠습니다.

**Comment by SanghooMoon** [comment]
@hwang434  완전 탐색 관련 자료가 백트래킹 자료네여~!

**Comment by hwang434** [comment]
> @hwang434 완전 탐색 관련 자료가 백트래킹 자료네여~!

수정했습니다~

**Comment by kaki5507** [comment]
내일 풀어볼게요 ~
