### ISSUE TITLE
01월 24일 ~ 01월 30일차 알고리즘 문제 출제

### ISSUE THREAD

**Issue by hwang434** [ROUTINE-STUDY/Algorithm#235]
원하시는 문제 원하는 개수만큼 푸시면 됩니다.
출제 문제 유형(필수) : 완전탐색, 구현

1. 완전탐색
- [완전탐색/브론즈3] : https://www.acmicpc.net/problem/9094
- [완전탐색/브론즈1] : https://www.acmicpc.net/problem/1145
- [완전탐색/브론즈1] : https://www.acmicpc.net/problem/2851
- [완전탐색/실버3] : https://www.acmicpc.net/problem/2548
- [완전탐색/실버1] : https://www.acmicpc.net/problem/14225
- [완전탐색/실버1] : https://www.acmicpc.net/problem/14888
- [완전탐색/골드5] : https://www.acmicpc.net/problem/2589
- [완전탐색/골드5] : https://www.acmicpc.net/problem/15686
- [완전탐색/골드5] : https://www.acmicpc.net/problem/14500

2. 구현
- [구현/브론즈5] : https://www.acmicpc.net/problem/10797
- [구현/브론즈5] : https://www.acmicpc.net/problem/9498
- [구현/브론즈3] : https://www.acmicpc.net/problem/10250
- [구현/실버5] : https://www.acmicpc.net/problem/10709 
- [구현/실버4] : https://www.acmicpc.net/problem/3048
- [구현/실버2] : https://www.acmicpc.net/problem/1713
- [구현/골드5] : https://www.acmicpc.net/problem/2636
- [구현/골드5] : https://www.acmicpc.net/problem/2174
- [구현/골드5] : https://www.acmicpc.net/problem/3190

### 잡답
선택해서 3문제를 목표로 풀면 좋을 것 같습니다!!

**Comment by SanghooMoon** [comment]
2022-01-24 : 완전탐색(B3) - 9094 - 수학적 호기심 완료
2022-01-25

**Comment by hwang434** [comment]
2022-01-24 : 
-완료-
[완전탐색/브론즈3] : https://www.acmicpc.net/problem/9094
[완전탐색/브론즈1] : https://www.acmicpc.net/problem/1145
[완전탐색/브론즈1] : https://www.acmicpc.net/problem/2851
[완전탐색/실버3] : https://www.acmicpc.net/problem/2548
[완전탐색/실버1] : https://www.acmicpc.net/problem/14225
