### ISSUE TITLE
2022년 11월 04일 ~ 11월 06일 알고리즘 문제 출제

### ISSUE THREAD

**Issue by SanghooMoon** [ROUTINE-STUDY/Algorithm#369]
원하시는 문제 원하는 개수만큼 푸시면 됩니다. (문제 추가 가능)

- [프로그래머스/LV2] : https://school.programmers.co.kr/learn/courses/30/lessons/12973

### 잡답
부활 기념 몸풀기 한 주 시작하시져!

**Comment by hwang434** [comment]
[프로그래머스/LV1] : https://github.com/ROUTINE-STUDY/Algorithm/pull/368
프로그래머스 부활 기념 간단한 문제 가즈아
